namespace zPoolMiner.Utils
{
    public static class Bins_Data
    {
        #region CODE_GEN STUFF // listFiles.py

        public static string[] ALL_FILES_BINS = {
            @"\AMD-NVIDIA\claymore_cryptonight\Data1a1.bin",
@"\AMD-NVIDIA\claymore_cryptonight\msvcr110.dll",
@"\AMD-NVIDIA\claymore_cryptonight\NsGpuCNMiner.exe",
@"\AMD-NVIDIA\claymore_cryptonight\Remote manager\EthMan.exe",
@"\AMD-NVIDIA\claymore_cryptonight\Remote manager\libeay32.dll",
@"\AMD-NVIDIA\claymore_cryptonight\Remote manager\ssleay32.dll",
@"\AMD-NVIDIA\claymore_dual\cudart64_80.dll",
@"\AMD-NVIDIA\claymore_dual\EthDcrMiner64.exe",
@"\AMD-NVIDIA\claymore_dual\libcurl.dll",
@"\AMD-NVIDIA\claymore_dual\msvcr110.dll",
@"\AMD-NVIDIA\claymore_dual\OpenCL.dll",
@"\AMD-NVIDIA\claymore_dual\cuda6.5\cudart64_65.dll",
@"\AMD-NVIDIA\claymore_dual\cuda6.5\EthDcrMiner64.exe",
@"\AMD-NVIDIA\claymore_dual\cuda7.5\cudart64_75.dll",
@"\AMD-NVIDIA\claymore_dual\cuda7.5\EthDcrMiner64.exe",
@"\AMD-NVIDIA\claymore_dual\cuda9.1\cudart64_91.dll",
@"\AMD-NVIDIA\claymore_dual\cuda9.1\EthDcrMiner64.exe",
@"\AMD-NVIDIA\claymore_dual\Remote manager\libeay32.dll",
@"\AMD-NVIDIA\claymore_dual\Remote manager\ssleay32.dll",
@"\AMD-NVIDIA\claymore_zcash\Data2.bin",
@"\AMD-NVIDIA\claymore_zcash\msvcr110.dll",
@"\AMD-NVIDIA\claymore_zcash\ZecMiner64.exe",
@"\AMD-NVIDIA\claymore_zcash\Remote manager\EthMan.exe",
@"\AMD-NVIDIA\claymore_zcash\Remote manager\libeay32.dll",
@"\AMD-NVIDIA\claymore_zcash\Remote manager\ssleay32.dll",
@"\AMD-NVIDIA\claymore_neoscrypt\NeoScryptMiner.exe",
@"\AMD\mkxminer\libcrypto-1_1.dll",
@"\AMD\mkxminer\libssl-1_1.dll",
@"\AMD\mkxminer\mkxminer.exe",
@"\AMD\mkxminer\msvcr120.dll",
@"\AMD\optiminer_zcash_win\Optiminer.exe",
@"\ccminer_tpruvot2\ccminer.exe",
@"\CPU\CPU-JayDDee\cpuminer-aes-sse42.exe",
@"\CPU\CPU-JayDDee\cpuminer-avx2.exe",
@"\AMD\sgminer-5-6-0-general\sgminer.exe",
@"\AMD\sgminer-gm\sgminer.exe",
@"\AMD\sgminer-HSR\sgminer.exe",
@"\AMD\sgminer-Phi\sgminer.exe",
@"\AMD\sgminer-Bitcore\sgminer.exe",
@"\AMD\sgminer-Skein\sgminer.exe",
@"\AMD\sgminer-Tribus\sgminer.exe",
@"\AMD\sgminer-Xevan\sgminer.exe",
@"\AMD\sgminer-aceneun\sgminer.exe",
@"\AMD\GLG\gatelessgate.exe",
@"\CPU\CPU-cpuminerOptBF\cpuminer-aes-sse42.exe",
@"\CPU\CPU-Cpupower\cpuminer-aes-sse42.exe",
@"\CPU\CPU-JayDDee\cpuminer-aes-sse42.exe",
@"\CPU\CPU-JayDDeeYespower\cpuminer-sse42.exe",
@"\CPU\CPU-nosuch\cpuminer-aes-sse2.exe",
@"\CPU\CPU-Verium\cpuminer.exe",
@"\CPU\CPU-RKZ\cpuminer.exe",
@"\CPU\CPU-rplant\cpuminer-aes.exe",
@"\CPU\CPU-SRBMiner\SRBMiner-MULTI.exe",
@"\CPU\CPU-XMRig\xmrig.exe",
@"\CPU\CPU-XMRigUPX\xmrig.exe",
@"\NVIDIA\NVIDIA-trex\t-rex.exe",
@"\NVIDIA\NVIDIA-CryptoDredge\CryptoDredge.exe",
@"\NVIDIA\NVIDIA-zealotenemy\z-enemy.exe",
@"\AMD-NVIDIA\claymore_zcash\ZecMiner64.exe",
@"\AMD-NVIDIA\claymore_neoscrypt\NeoScryptMiner.exe",
@"\AMD-NVIDIA\claymore_cryptonight\NsGpuCNMiner.exe",
@"\AMD\optiminer_zcash_win\Optiminer.exe",
@"\AMD-NVIDIA\claymore_dual\EthDcrMiner64.exe",
@"\AMD\mkxminer\mkxminer.exe",
@"\vc_redist.x64.exe",

};

        #endregion CODE_GEN STUFF // listFiles.py
    }
}